// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiywektloktmnpdomndh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpeXdla3Rsb2t0bW5wZG9tbmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1OTQwODUsImV4cCI6MjA3NjE3MDA4NX0.mLRsQ8nuZ6sFiqUH4wOekCrx3tjmwPTsE7BwkY3rh4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});